### ISSUE TITLE
when validating a run is complete use the actual number of tiles in each lane

### ISSUE THREAD

**Issue by srl147** [wtsi-npg/npg_tracking#330]
when validating a run is complete ( see validate_run_complete() in lib/Monitor/RunFolder/Staging.pm ) we check the expected number of tiles are present. The expected number of tiles is assumed to be the same for each lane, this is not the case if some tiles are missing. The number of tiles for a particular lane can be derived from Data/Intensities/config.xml

**Comment by mgcam** [comment]
This has been implemented, see https://github.com/wtsi-npg/npg_tracking/blob/bcc602d3c51b786b26971869ae4e529c2123586f/lib/npg_tracking/illumina/run/long_info.pm#L381
