### ISSUE TITLE
unable to run web server under httpd 2.4.25

### ISSUE THREAD

**Issue by mgcam** [wtsi-npg/npg_tracking#405]
Suggested remedy like

PerlInitHandler Apache2::Reload
PerlSetVar ReloadAll Off

does not help.

It seems that Perl modules are reloaded when a second request is made on a fork.

modperl library compiled for 2.4.25 is OK, since httpd 2.4.23 can run with it

httpd 2.4.25 cannot run either with modperl compiled for it or the one compiled for v2.4.23

**Comment by jmtcsngr** [comment]
Likely to be related to https://github.com/wtsi-npg/npg_tracking/issues/409.
From 2.4.23 to 2.4.25+ mpm_event became the default and we were lacking the specific configuration for the module.
